### ISSUE TITLE
Connect Sign in / register to API

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/googleMaps-offline-navigator#125]
connect the client side sign in and register forms to the users resource on the API server.

**Comment by seckboy** [comment]
I can try to help with this.

**Comment by seckboy** [comment]
I'm trying to connect to localhost:8080/users/register using postman. Since I am not sending any parameters I am expecting a 400 response saying 'One or more fields were left empty' but I must be doing something wrong. I am able to get the home page through postman but I just get a 404 not found saying Cannot POST /users/register.
![postman.users.register.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6cdc4633b3320011270466/125516c66e82c728ace21e0d46f89b89378f82a7c1fcac46b64ebe862c412e603d01b1693cc7f33ab0487e021b4d44be44095944fdf9892da4b26a2582550bedd5395c22c43418afaa9e0dfd50e474d412dcfce9c85ecafa3c22ed8a8a4e36170c1e8cf65533a3905985.png)

**Comment by motosharpley** [comment]
@seckboy in postman you are contacting the api directly and need to use port 8081

**Comment by seckboy** [comment]
The tests for the client were not running.  Actually the only test was for the Nav component. So in the Nav component, I commented out the first 2 lines below and replaced with the third line and the tests ran:

// import Menu from 'preact-material-components/Menu';
// import Button from 'preact-material-components/Button';
import { Menu, Button } from 'preact-material-components';

I'll check this change in whenever I finish this issue. Until we replace preact-material-components, at least we can now write tests for the client.

**Comment by motosharpley** [comment]
@seckboy Ok cool good to know We should be able to refactor this out soon. I think we will end up on the react-semantic-ui or vanilla css and styletron or a combiniation of the two I'm working through some testing to figure out our best option.
This one looks pretty good though https://react.semantic-ui.com/introduction
