### ISSUE TITLE
Add notifications to sign in / register

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/googleMaps-offline-navigator#180]
incorporate notification messages for success and errors on  sign in, sign out and register.

**Comment by seckboy** [comment]
You can assign this to me. I have been refactoring signin and register to use preact setState instead of how it was doing it before (old fashioned getElementById). I have also tweaked the profile page to get user info and display their name and a success message if they are coming from register or sign in.

**Comment by motosharpley** [comment]
@seckboy that's great,
Thank you!
