### ISSUE TITLE
Set up API Routes

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/googleMaps-offline-navigator#39]
Work with reference docs to map out necessary routes and incorporate into express api.

**Comment by jkwening** [comment]
Starting on skeleton for this and will create new issues for specific tasks. I believe based on current mockups we're going to need the following:

#### Routes
* users - for handling user authentication tasks (#38)
    * I'll probably create a file in my first PR but will leave in @D1esel-Dev hands since it looks like he's already on top of that
* search - handles search queries, query results, and saved pins and directions tasks
    * I'll create a separate issue for this
* map - handles tasks related to displaying the map including directions and pins
    * I'll get started on this

#### Controllers
* users
* saved-directions: related to search route
* saved-pins: related to search route
* search-history: related to search route
* map: will handle calls to Google Maps API and internals related to map view

#### Notes
Alternatively, we could collapse the 'search' route into the 'map' route since we would make calls to Google API for search results but thought it would be best to keep separate since the result view would be list of viable results and user would select one that would then lead to map view.

**Comment by jkwening** [comment]
Closing this issue since skeleton code base has been deployed and task broken into modular issues: #57, #58, #59, and #60.
