### ISSUE TITLE
Search component

### ISSUE THREAD

**Issue by pjdmatts** [TheDevPath/googleMaps-offline-navigator#82]
Feature Request

Please create a Preact Search Component for the UI.

For the attention of @TheDevPath/front-end-dev-team

**Comment by jkwening** [comment]
Should consider incorporating googmaps places autocomplete feature: https://developers.google.com/maps/documentation/javascript/places-autocomplete

**Comment by khusbuchandra** [comment]
Before starting on it, I have got a question. This search component feature request is supposed to be just the text input with hamburger menu button or does it also include the menu also? Since I didn't find the issue raised for Menu component, want my assumptions to be clarified.
I am going to try my hand on it, any other pointers that might help me to get started.

**Comment by motosharpley** [comment]
You can just start with the the search input and we can add additional issues or expand on the pull request as needed.

**Comment by motosharpley** [comment]
just putting this here for safe keeping https://github.com/googlemaps/google-maps-services-js

**Comment by khusbuchandra** [comment]
@Bryan , I did try that but was getting stuck with createClient which needed process and wasn't getting it. 
 For the time being i found a working solution with script injection.  I did try lot of other libraries but somehow they weren't working for us. If someone wants to try their hand with a better solution, feel free, I will be eager to learn more.
